export const ACTION_TYPES = {
  FETCH_BOOK_STARTED: "FETCH_BOOK_STARTED",
  FETCH_BOOK_FAILED: "FETCH_BOOK_FAILED",
  RESET_STATE: "RESET_STATE",

  FETCH_BOOK: "FETCH_BOOK",
  ADD_BOOK: "ADD_BOOK",
  EDIT_BOOK: "EDIT_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
};
