export const ACTION_TYPES = {
  FETCH_BOOK_REQUEST: "FETCH_BOOK_REQUEST",
  FETCH_BOOK_SUCCESS: "FETCH_BOOK_SUCCESS",
  FETCH_BOOK_ERROR: "FETCH_BOOK_ERROR",

  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
  CREATE_BOOK_ERROR: "CREATE_BOOK_ERROR",

  UPDATE_BOOK_SUCCESS: "UPDATE_BOOK_SUCCESS",
  UPDATE_BOOK_ERROR: "UPDATE_BOOK_ERROR",

  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_ERROR: "DELETE_BOOK_ERROR",

  RESET_BOOK_STATE: "RESET_BOOK_STATE",
};

